"""Migration éditoriale initiale (ne pas relancer après modifications manuelles)."""
import json,re
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
def read(p):return (ROOT/p).read_text(encoding='utf-8-sig')
def write(p,s):(ROOT/p).write_text(s,encoding='utf-8')
site=json.loads(read('src/data/site.json'))
site.update(whatsapp='',prices={},reviews_api={'enabled':False,'place_id':'','endpoint':'/api/reviews.php'})
site['google'].update(review_count=448,checked_on='2026-09-28')
site['photos']=json.loads(read('tools/photo-results.json'))
site['photos']['vente']=dict(site['photos']['imprimante'])
site['reviews']=[
 dict(author='Nathan M.',initial='N',rating=5,date=None,date_label='Vers juin 2026',text='Merci à l’équipe de Digital-Buro pour le professionnalisme et l’efficacité de leurs réparations.',tags=['pc'],response='',source=site['google']['cid_url']),
 dict(author='Corine S.',initial='C',rating=5,date=None,date_label='Vers juillet 2026',text='Le monsieur était tres accueillant et bienveillant. Il est de bon conseil et la qualité des produits est géniale.',tags=['vente','accueil'],response='',source=site['google']['cid_url']),
 dict(author='Michael M.',initial='M',rating=5,date=None,date_label='Vers mars 2026',text='Une expérience fantastique chez Digital Buro sur la Chaussée de Charleroi ! ⭐',tags=['accueil'],response='',source=site['google']['cid_url'])]
teasers={
 'imprimante':'Bourrage, traces, code erreur : retrouvons le plaisir d’imprimer.',
 'ordinateur':'PC lent, écran cassé ou batterie fatiguée : on regarde ça.',
 'mac':'MacBook, iMac, Mac mini : une seconde vie pour votre Mac.',
 'gsm':'Écran, batterie, charge : parlons de votre smartphone ou tablette.',
 'cartouches':'La bonne référence, même pour votre ancienne imprimante.',
 'entreprises':'Votre bureau continue de tourner. Intervention sur site à Bruxelles.',
 'vente':'Le bon matériel, conseillé, installé et configuré.'}
for s in site['services']:s['teaser']=teasers[s['key']]

def faq(q,a):return [q,'<p>'+a+'</p>']
price=faq('Quel budget prévoir ?', 'Le coût dépend du modèle, de la panne et des pièces. Demandez les conditions du diagnostic avant de déposer votre appareil. Le devis vous permet de décider de la suite, sans mauvaise surprise sur les travaux envisagés.')
delay=faq('Quel est le délai ?', 'Le délai dépend du diagnostic et des pièces disponibles pour votre modèle. Contactez-nous avec sa référence : nous vous indiquerons comment organiser la prise en charge, puis les possibilités de réparation après examen.')
content={
'imprimante':dict(tag='LE CŒUR DE NOTRE MÉTIER',h1='Réparation d’imprimantes à Saint-Gilles.',lead='Bourrages, traces, erreurs : redonnons de belles pages à votre imprimante.',device='Imprimante',photo='imprimante',eyebrow='LASER, JET D’ENCRE ET PHOTOCOPIEURS',heading='Elle imprime mal ? On regarde.',intro=['Votre imprimante bloque le travail à la maison ou au bureau ? Digital-Buro prend en charge imprimantes et photocopieurs toutes marques à Saint-Gilles, près de Ma Campagne.', 'Laser, jet d’encre, multifonction ou ancienne matricielle : indiquez-nous le modèle et le défaut observé. L’expérience du dirigeant aide à reconnaître les pannes et à orienter le diagnostic.'],symptoms=[['paper-jam','Bourrage papier'],['lines','Traces sur la feuille'],['droplet','Couleurs manquantes'],['alert','Code erreur'],['power','Ne s’allume plus'],['wifi','Imprimante introuvable'],['scan','Scanner bloqué'],['thermometer','Toner qui s’efface']],brands=['HP','Canon','Epson','Brother','OKI','Xerox','Ricoh','Kyocera'],note='Photocopieur difficile à transporter ? Demandez une intervention dans vos locaux à Bruxelles.',review_tag='imprimante',faq=[price,faq('Réparer ou remplacer ?', 'L’état de la machine, son usage et les pièces disponibles comptent autant que son âge. Après diagnostic, comparez le devis au remplacement. Nous pouvons aussi vous conseiller une imprimante adaptée à votre volume d’impression.'),faq('Que faut-il apporter ?', 'Notez le modèle et le code erreur. Une page montrant les traces ou les couleurs manquantes nous aide beaucoup. Appelez avant de transporter un appareil lourd ou encombrant.'),faq('Et les cartouches des anciens modèles ?', 'Nous proposons des cartouches, toners, tambours et rubans, y compris pour des modèles anciens. Apportez la référence de votre consommable ou une photo de l’étiquette de l’imprimante pour vérifier la compatibilité et la disponibilité.')],advice='Pour préparer votre visite, notez quand le défaut apparaît : au démarrage, pendant l’impression ou au scan. Évitez de démonter la machine. Nous vous aidons à choisir entre entretien, réparation et remplacement selon votre besoin.',related=['cartouches','vente','entreprises']),
'ordinateur':dict(tag='PC FIXES & PORTABLES · TOUTES MARQUES',h1='Réparation de PC à Saint-Gilles.',lead='Un PC qui ralentit, s’éteint ou ne démarre plus ? Parlons-en.',device='PC portable',photo='ordinateur',eyebrow='VOTRE ORDINATEUR PEUT ENCORE SERVIR',heading='Retrouvez un PC agréable à utiliser.',intro=['Pour travailler, étudier ou gérer le quotidien, un ordinateur en panne complique tout. Notre magasin de Saint-Gilles vous accompagne pour la réparation de PC fixes et portables, toutes marques.', 'Un écran abîmé, une batterie usée ou des lenteurs ne demandent pas la même intervention. Expliquez ce qui a changé et donnez le modèle : nous orientons la prise en charge.'],symptoms=[['laptop','Écran cassé'],['battery','Batterie fatiguée'],['power','Démarrage impossible'],['settings','PC lent'],['thermometer','Surchauffe'],['wifi','Connexion instable'],['shield','Logiciels indésirables'],['keyboard','Clavier défectueux']],brands=['HP','Dell','Lenovo','Asus','Acer','Toshiba','Samsung'],note='Votre PC fonctionne encore sous Windows 10 ? Vérifions sa compatibilité avec Windows 11 avant d’envisager la migration.',review_tag='pc',faq=[price,faq('Un PC lent doit-il être remplacé ?', 'Pas forcément. Le stockage, la mémoire ou les logiciels peuvent expliquer les lenteurs. Selon le modèle, une remise en état ou une évolution du matériel peut être envisageable. Nous discutons des options après diagnostic.'),faq('Comment préparer mes données ?', 'Sauvegardez vos fichiers si l’ordinateur fonctionne encore. Signalez les documents importants et vos besoins avant toute intervention. Une récupération dépend de l’état du support : aucun résultat ne peut être promis avant examen.'),faq('Mon ordinateur peut-il passer à Windows 11 ?', 'Cela dépend de sa configuration et des exigences de Microsoft. Nous vérifions la compatibilité du modèle avant de proposer une migration. Pensez à sauvegarder vos documents et à signaler les logiciels dont vous avez besoin.')],advice='Apportez le chargeur de votre portable et décrivez les symptômes. Précisez si le souci apparaît sur batterie, au branchement ou avec un logiciel particulier. Ces informations facilitent le diagnostic et évitent les essais inutiles.',related=['mac','vente','entreprises']),
'mac':dict(tag='MACBOOK · IMAC · MAC MINI',h1='Réparation de Mac à Saint-Gilles.',lead='Votre Mac mérite de retrouver son rythme. Voyons ce qui le ralentit.',device='Mac',photo='mac',eyebrow='UNE SECONDE VIE POUR VOTRE MAC',heading='Le bon diagnostic, pour votre modèle.',intro=['Vous utilisez un MacBook, un iMac ou un Mac mini à Bruxelles ? Digital-Buro vous accueille à Saint-Gilles pour faire le point sur une panne, une batterie fatiguée ou un problème de fonctionnement.', 'Chaque génération de Mac a ses particularités. Précisez le modèle et l’année : nous vérifions les possibilités d’intervention et de remplacement des pièces avant de vous orienter.'],symptoms=[['monitor','Écran endommagé'],['battery','Autonomie réduite'],['keyboard','Touches défaillantes'],['power','Mac qui ne démarre plus'],['settings','macOS instable'],['thermometer','Ventilation bruyante']],brands=['MacBook Air','MacBook Pro','iMac','Mac mini'],note='Réparateur indépendant. La prise en charge dépend du modèle et des pièces disponibles.',review_tag='mac',faq=[price,delay,faq('Faut-il apporter le chargeur ?', 'Oui, pour un MacBook, le chargeur aide à distinguer un problème d’alimentation d’une panne de batterie. Notez aussi les symptômes : écran noir, extinction, bruit inhabituel ou autonomie réduite, et le moment où ils apparaissent.'),faq('Mes fichiers seront-ils conservés ?', 'Faites une sauvegarde avant de confier votre Mac si vous le pouvez. Indiquez les données à préserver et les opérations autorisées. Les possibilités de récupération dépendent du modèle et de l’état du stockage ; elles nécessitent un diagnostic.')],advice='Avant de venir, relevez les informations disponibles dans « À propos de ce Mac » ou sur l’étiquette de l’appareil. Ne communiquez pas vos mots de passe par le formulaire. Nous préciserons avec vous ce qui est nécessaire à l’intervention.',related=['ordinateur','vente','entreprises']),
'gsm':dict(tag='SMARTPHONES & TABLETTES',h1='Réparation de GSM à Saint-Gilles.',lead='Écran cassé, charge impossible ? Commençons par le modèle de votre téléphone.',device='GSM / tablette',photo='gsm',eyebrow='VOTRE TÉLÉPHONE AU QUOTIDIEN',heading='Un souci qui vous bloque ?',intro=['Un smartphone ou une tablette accompagne les appels, les photos et le travail. Pour une réparation de GSM à Saint-Gilles, contactez Digital-Buro avec la marque et le modèle de votre appareil.', 'Le type d’écran, la batterie et le connecteur varient selon les versions. Nous vérifions les possibilités de prise en charge et la disponibilité des pièces avant de vous proposer la suite.'],symptoms=[['smartphone','Écran fissuré'],['battery','Batterie qui se vide'],['power','Ne s’allume plus'],['settings','Charge impossible'],['alert','Affichage défectueux'],['droplet','Contact avec un liquide']],brands=['Apple','Samsung','Huawei','Xiaomi'],note='Sauvegardez vos photos et vos contacts avant toute intervention, si l’appareil le permet.',review_tag='gsm',faq=[price,delay,faq('Mon téléphone a pris l’eau, que faire ?', 'Éteignez-le et ne le mettez pas en charge. Évitez de le chauffer ou de le démonter. Contactez-nous en précisant ce qui s’est passé. L’étendue des dommages et les possibilités de réparation ne peuvent être évaluées qu’après examen.'),faq('Réparez-vous mon modèle de tablette ?', 'Appelez avec la référence exacte, généralement visible dans les réglages ou au dos. La prise en charge dépend du modèle, de la panne et des pièces disponibles. Nous vous indiquons les informations utiles avant votre déplacement.')],advice='Décrivez le problème simplement : la batterie se vide, le câble ne tient plus ou une partie de l’écran ne répond pas. Indiquez toute chute ou exposition à un liquide. N’envoyez ni code de déverrouillage ni mot de passe via le formulaire.',related=['ordinateur','mac','cartouches']),
'cartouches':dict(tag='ENCRE, TONER & CONSOMMABLES',h1='Cartouches et toners à Saint-Gilles.',lead='La bonne référence pour votre imprimante. Même si elle a quelques années.',device='Cartouche / toner',photo='cartouches',eyebrow='LE SPÉCIALISTE DES CONSOMMABLES',heading='Vous imprimez. On vous équipe.',intro=['À la recherche d’une cartouche d’encre, d’un toner ou d’un ruban à Bruxelles ? Notre magasin de Saint-Gilles propose un grand choix de consommables pour imprimantes, photocopieurs et machines de bureau.', 'Apportez votre ancienne cartouche ou la référence de la machine. Nous vous aidons à identifier le bon produit, notamment pour les modèles anciens dont les références sont parfois difficiles à retrouver.'],symptoms=[['droplet','Cartouches d’encre'],['printer','Toners laser'],['settings','Tambours'],['paper','Rubans'],['scan','Consommables pour copieurs'],['building','Fournitures pour bureaux']],brands=['HP','Canon','Epson','Brother','OKI','Lexmark','Ricoh'],note='Une référence précise ? Appelez avant de venir pour vérifier le stock.',review_tag='cartouches',faq=[faq('Comment trouver la bonne cartouche ?', 'Relevez la référence sur l’ancienne cartouche et le modèle exact de l’imprimante. Une photo nette de chaque étiquette est utile. Le nom de la marque seul ne suffit pas à garantir la compatibilité.'),faq('Avez-vous des références anciennes ?', 'Nous proposons aussi des consommables pour des machines anciennes : encre, toner et rubans. Leur disponibilité dépend de la référence. Contactez-nous avant de vous déplacer pour que nous vérifiions le produit recherché.'),faq('Toner ou tambour : que remplacer ?', 'Le toner contient la poudre d’impression ; le tambour participe au transfert de l’image. Ils sont séparés sur certains modèles. Notez le message affiché par l’imprimante afin de ne pas remplacer le mauvais consommable.'),faq('Livrez-vous les entreprises ?', 'Digital-Buro propose la livraison de consommables aux professionnels. Contactez-nous avec vos références, quantités et adresse à Bruxelles pour connaître les possibilités et conditions adaptées à votre bureau.')],advice='Une cartouche neuve ne résout pas toutes les pannes d’impression. Si les traces persistent ou si la machine affiche une erreur, décrivez le défaut au magasin. Nous pouvons vous orienter vers un diagnostic plutôt que vers un achat inutile.',related=['imprimante','vente','entreprises']),
'vente':dict(tag='CHOISIR LE BON MATÉRIEL',h1='Matériel informatique à Saint-Gilles.',lead='Une imprimante, un PC, un bureau à équiper ? Partons de vos besoins.',device='Achat de matériel',photo='vente',eyebrow='DU CONSEIL À L’INSTALLATION',heading='Bien équipé, tout simplement.',intro=['Digital-Buro propose la vente de matériel bureautique et informatique à Saint-Gilles : imprimantes, photocopieurs, scanners et ordinateurs. Nous vous aidons à choisir selon votre usage et votre budget.', 'Pour la maison ou votre entreprise à Bruxelles, pensez au coût des consommables, aux connexions et à la place disponible. Ces détails comptent autant que la fiche technique pour choisir un appareil agréable à utiliser.'],symptoms=[['printer','Imprimantes'],['scan','Photocopieurs & scanners'],['laptop','PC portables'],['monitor','Ordinateurs de bureau'],['wifi','Matériel réseau'],['package','Fournitures & accessoires']],brands=['HP','Canon','Epson','Brother','Dell','Lenovo'],note='Votre usage, votre budget, vos consommables : trois repères pour un achat adapté.',review_tag='vente',faq=[faq('Laser ou jet d’encre ?', 'Le volume de pages, la fréquence d’utilisation et le besoin de couleur orientent le choix. Indiquez ce que vous imprimez : documents de bureau, photos ou travaux scolaires. Nous comparons les possibilités en tenant compte des consommables.'),faq('Installez-vous le matériel ?', 'Nous proposons l’installation et la configuration de matériel de bureau. Contactez-nous pour préciser les appareils à raccorder, votre réseau et votre adresse. Les modalités se définissent selon les besoins de votre installation.'),faq('Pouvez-vous équiper une entreprise ?', 'Oui. Imprimantes, photocopieurs, ordinateurs et consommables peuvent être étudiés ensemble. Expliquez le nombre d’utilisateurs, les documents imprimés et les besoins du bureau pour que nous vous orientions vers une solution adaptée.'),faq('Comment connaître les prix ?', 'Appelez ou envoyez votre besoin par le formulaire. Les modèles, les configurations et la disponibilité font varier les prix. Un échange au magasin permet de comparer les options et de préciser les frais d’installation éventuels.')],advice='Vous remplacez un appareil existant ? Apportez sa référence et notez ce qui vous convient ou vous manque. Nous examinerons avec vous le format, les usages et les possibilités d’entretien pour préparer votre achat.',related=['imprimante','cartouches','entreprises']),
'entreprises':dict(tag='INDÉPENDANTS, ASSOCIATIONS & PME',h1='Dépannage informatique pour entreprises à Bruxelles.',lead='Une panne ne devrait pas arrêter votre bureau. Parlons de votre installation.',device='Entreprise',photo='entreprises',eyebrow='UN INTERLOCUTEUR POUR VOTRE BUREAU',heading='Vos outils doivent suivre votre rythme.',intro=['Basé à Saint-Gilles, Digital-Buro accompagne les professionnels de Bruxelles pour l’entretien et la réparation de leur matériel de bureau. Imprimantes, photocopieurs, informatique et consommables : les besoins se traitent avec un même interlocuteur.', 'Décrivez le matériel concerné, les utilisateurs touchés et le problème rencontré. Nous vous indiquons comment organiser le diagnostic et, selon le besoin, une intervention dans vos locaux ou à l’atelier.'],symptoms=[['printer','Imprimante partagée en panne'],['wifi','Réseau & Wi-Fi'],['settings','Entretien du matériel'],['laptop','Postes de travail'],['package','Livraison de consommables'],['building','Installation sur site']],brands=['HP','Canon','Brother','Ricoh','Kyocera','Dell','Lenovo'],note='Saint-Gilles, Ixelles, Forest, Uccle et Bruxelles : contactez-nous pour organiser une intervention.',review_tag='entreprises',faq=[faq('Intervenez-vous dans nos locaux ?', 'Oui, Digital-Buro propose des interventions sur site à Bruxelles, notamment pour les machines de bureau et le réseau. Communiquez l’adresse, le modèle et les symptômes afin de convenir des modalités et d’un passage.'),faq('Proposez-vous un entretien régulier ?', 'Nous pouvons étudier l’entretien de votre matériel de bureau selon son usage. Indiquez les machines, leur ancienneté et votre volume d’impression. Le périmètre et la fréquence se définissent avec vous.'),faq('Pouvez-vous installer un nouveau bureau ?', 'Nous proposons la vente, l’installation et la configuration de matériel informatique et bureautique. Décrivez vos postes, imprimantes et besoins de connexion : nous vous aidons à préparer un équipement cohérent pour votre activité.'),faq('Comment demander une intervention ?', 'Appelez le 02 534 47 02 ou utilisez le formulaire en choisissant « Entreprise ». Précisez le modèle, le message d’erreur et le nombre d’utilisateurs concernés. N’envoyez pas de mots de passe.')],advice='Pour une panne qui touche plusieurs personnes, notez si elle concerne tous les postes ou une seule machine. Signalez les changements récents : nouveau routeur, nouvel ordinateur ou déplacement d’une imprimante. Cela aide à cibler les premières vérifications.',related=['imprimante','ordinateur','cartouches'])}
for key,c in content.items():
 c['process_title']='Du premier échange à la solution.'
 c['faq_title']='Vos questions, nos réponses.'
site['service_content']=content
write('src/data/site.json',json.dumps(site,ensure_ascii=False,indent=2)+'\n')
pages=json.loads(read('src/data/pages.json'))
for page in pages:
 if page['type']=='service':write('src/pages/'+page['template'],'{% extends "service-compact.html" %}\n')

# Three steps; the longer details live in the service FAQ.
s=read('src/templates/macros.html')
start=s.index('{% macro process()')
end=s.index('{%- endmacro %}',start)+len('{%- endmacro %}')
s=s[:start]+'''{% macro process() -%}
<ol class="steps" role="list">
{% set steps = [('Vous nous contactez', 'Un appel ou un passage au magasin pour parler de votre appareil.'), ('Diagnostic et devis', 'La panne identifiée, vous choisissez la suite.'), ('Votre appareil repart', 'La réparation convenue, votre machine retrouve son utilité.')] %}
{% if page.lang == 'en' %}{% set steps = [('Get in touch','Call or visit to tell us about your device.'),('Diagnosis and estimate','Understand the problem and choose the next step.'),('Back in service','We carry out the agreed repair.')] %}{% elif page.lang == 'nl' %}{% set steps = [('Neem contact op','Bel of kom langs om uw toestel te bespreken.'),('Diagnose en offerte','U kent het probleem en kiest de volgende stap.'),('Weer aan het werk','We voeren de afgesproken herstelling uit.')] %}{% endif %}
{% for title,desc in steps %}<li class="step"><span class="step__num">0{{ loop.index }}</span><h3 class="step__title">{{ title }}</h3><p class="step__text">{{ desc }}</p></li>{% endfor %}
</ol>{%- endmacro %}'''+s[end:]
write('src/templates/macros.html',s)
for name in ['header','footer']:
 p='src/templates/partials/'+name+'.html';s=read(p).replace('width="139" height="26"','width="140" height="36"');write(p,s)
p='src/templates/partials/header.html';s=read(p);s+='<noscript><nav class="no-js-nav" aria-label="Navigation sans JavaScript"><a href="/">Accueil</a> · <a href="/reparation-imprimante/">Imprimantes</a> · <a href="/reparation-ordinateur/">PC</a> · <a href="/contact/">Contact</a></nav></noscript>\n';write(p,s)
p='src/templates/partials/callbar.html';s=read(p);s=s.replace('</div>','{% if site.whatsapp %}<a class="btn btn--outline" href="https://wa.me/{{ site.whatsapp|e }}" data-track="whatsapp" target="_blank" rel="noopener">WhatsApp</a>{% endif %}\n</div>');write(p,s)
# Clearly label generic reviews when no real matching review is available.
p='src/templates/partials/fresh-macros.html';s=read(p);anchor='<section class="section reviews-section"';idx=s.index(anchor);s=s[:idx]+'{% set filtered = selected.items|length > 0 %}{% if not selected.items %}{% set selected.items = site.reviews %}{% endif %}\n'+s[idx:];s=s.replace('<p class="caption review-disclosure">','<p class="caption review-disclosure">{% if tag and not filtered %}Avis sur le magasin, tous services confondus. {% endif %}Extraits. ');write(p,s)
# Article enhancement without hiding the SEO content.
p='src/pages/guide-impression.html';s=read(p).replace('<article>','<article data-reading>');s=s.replace('<div class="prose">','''<div class="prose">
<aside class="callout"><strong>L’essentiel en 30 secondes</strong><p>Le laser fixe une poudre, le toner, grâce à la chaleur. Le jet d’encre projette de petites gouttes. Des traces ou des couleurs manquantes peuvent venir de plusieurs pièces : le diagnostic évite de remplacer le mauvais consommable.</p></aside>
<div class="laser-diagram" data-reveal aria-label="Les six étapes de l’impression laser">{% for label in ['Nettoyer','Charger','Écrire','Développer','Transférer','Fixer'] %}<div style="--i:{{ loop.index0 }}"><b>0{{ loop.index }}</b>{{ label }}</div>{% endfor %}</div>''');write(p,s)
print('Contenus et composants mis à jour.')
